# UDP服务配置
server:
  ip: "127.0.0.1"
  port: 10006
  recv_len: 1024

# redis配置
redis:
  host: redis
  port: 6379
  password: 123456
  db: 1
  maxIdle: 30
  maxActive: 30
  idleTimeout: 200

# 日志配置
logger:
  level: DEBUG
  pretty: true
  color: true
